spring:
  datasource:
    url: jdbc:postgresql://ep-sparkling-poetry-agddtkne-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_JR7VW4QjtDLk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 10000

jwt:
  secret: ${JWT_SECRET:dev_super_secret_key_32bytes_min_ok__}
