spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eduplus_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create   # dev: svaki put svježe + naš seeder popuni
    show-sql: true

jwt:
  secret: dev_super_secret_key_32bytes_min__ok__
